### ISSUE TITLE
In correct bvals and bvecs for GE sites

### ISSUE THREAD

**Issue by meet10may** [a2cps/mri_imaging_pipeline#25]
The GE sites i.e. UIC and UMs have incorrect bvals and bvecs, 
Currently, the bvals after conversion from Heudiconv is 

`0 0 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000 3000`

and bvec is 
`0 0 0.161294 0.188064 0.830777 0.102332 -0.638642 -0.433159 0.787992 -0.047734 0.005645 -0.107663 0.100941 0.485282 -0.279988 -0.705673 0.832286 -0.900149 -0.142649 -0.767194 0.993264 0.929906 -0.739788 0.428977 -0.503193 -0.155615 -0.433904 0.499575 -0.242905 0.266256 0.704088 0.097701 -0.923526 -0.473095 0.59125 -0.40594 -0.57841 0.496678 -0.693364 0.728049 0.47936 0.638003 0.192998 0.40712 0.105095 -0.852526 0.410067 -0.534927 0.588382 0.104389 -0.990392 -0.62683 -0.697274 -0.161024 -0.301863 -0.086347 -0.271032 0.902452 -0.976598 0.738525 0.612122 0.959947 0.198226 -0.125248 -0.397829 0.684667 -0.725229 0.845291 -0.919232 0.377209 0.499969 0.061731 -0.135764 -0.150356 0.961914 0.263165 -0.610891 -0.476073 -0.874806 -0.861236 0.792567 0.709123 0.862387 -0.059071 0.281305 -0.743013 -0.802846 -0.481176 0.440131 0.312225 0.648623 0.602526 -0.093211 0.314284 -0.442735 -0.390788 -0.192572 0.261067 0.910359 -0.940864 -0.727863 0.185058 -0.467147 -0.266994
0 0 0.984413 -0.420915 -0.044493 0.275011 -0.542789 0.829786 -0.396868 -0.066858 0.611668 0.543043 0.296069 0.85205 0.249639 -0.179454 -0.242853 0.417627 0.80302 -0.040865 0.103784 0.206082 -0.651301 0.882652 -0.26232 0.012094 -0.403412 -0.77807 0.34609 0.778156 0.705615 -0.876162 0.316629 0.770577 -0.258355 -0.077972 -0.702 -0.239752 0.708038 0.365562 -0.582422 -0.690685 0.663351 -0.900569 -0.667302 0.08801 0.396005 -0.84002 0.66792 0.949306 0.060952 0.331653 0.557448 -0.340016 -0.943532 -0.884417 -0.845783 0.428267 -0.040096 0.603649 -0.49332 -0.23494 0.882955 0.833168 -0.578296 0.362453 -0.403373 0.436295 -0.207547 0.507881 0.667803 -0.987031 -0.975198 0.954646 -0.161686 -0.366505 0.201176 -0.793928 0.218207 -0.337613 -0.539591 0.012652 -0.495605 -0.668365 -0.834037 0.635263 -0.564774 0.072909 0.164184 -0.019262 -0.759543 0.104864 -0.404466 -0.668311 0.546766 0.626138 0.973631 -0.949848 0.101604 -0.338189 0.451431 -0.077061 0.880634 -0.68459
0 0 -0.070114 0.887391 -0.554825 -0.95598 -0.545451 0.351894 -0.470706 -0.99662 0.791094 -0.832774 0.949818 -0.196244 -0.926978 -0.685436 0.498319 0.12377 -0.578628 0.640112 0.051533 -0.304639 -0.16888 0.192103 0.823399 0.987744 -0.805596 0.380831 0.906211 0.568842 0.079796 0.472012 -0.216438 -0.427075 -0.763987 -0.910568 0.415497 0.834164 0.133896 -0.579922 -0.656505 -0.340451 -0.722992 -0.152407 -0.737335 -0.515222 -0.821599 0.090663 0.45573 0.296515 0.124132 0.705046 0.450622 0.926532 -0.136476 -0.458639 0.459556 -0.046559 -0.211303 -0.300316 0.618014 0.152662 -0.425555 0.53865 0.712254 0.632344 0.557973 0.30843 0.334569 0.774449 -0.551425 -0.148185 0.174807 -0.25699 -0.220407 -0.892423 -0.765728 -0.378198 0.432551 -0.379856 0.28404 0.704972 -0.103269 0.741484 -0.474605 -0.210648 0.190969 0.873587 0.882796 -0.949813 0.048815 -0.79118 -0.909791 0.67423 -0.710657 0.674711 0.122304 0.172143 0.401152 -0.020069 -0.516165 0.979702 -0.079101 -0.67827`

and this has been tested with multiple versions of `dcm2nii (v1.0.20201102,v1.0.20210317,v1.0.20210928)`, and none of the versions create correct bvals and bvecs. 
I guess this is a known [issue](https://github.com/rordenlab/dcm2niix/issues/245#issuecomment-463627592) 
Maybe we need to ask Chris Roden about this at some time? Additionally, the MR software version is `DV26.0_R02_1810.b`.

The correct bvals are `0 0 0 3000 3000 2000 3000 1000 3000 3000 2000 3000 1000 3000 3000 500 3000 2000 3000 3000 1000 3000 500 3000 3000 2000 3000 1000 3000 3000 2000 3000 1000 3000 3000 0 3000 2000 3000 1000 3000 3000 500 3000 2000 3000 3000 1000 3000 0 3000 3000 2000 3000 1000 3000 3000 2000 3000 1000 3000 3000 500 3000 2000 3000 3000 1000 3000 0 3000 2000 3000 3000 1000 3000 500 3000 3000 2000 3000 1000 3000 3000 2000 3000 1000 3000 3000 0 3000 2000 3000 3000 1000 3000 500 3000 3000 2000 3000 1000 3000 0`

and the correct bvec is 

`0 0 0 -0.654875 -0.271924 0.957387 0.11881 0.957388 0.326879 -0.394817 -0.190618 0.906253 -0.190617 0.56633 -0.55854 -0.0062266 0.648904 -0.325492 0.435216 -0.060085 0.325492 0.290295 -0.636679 0.008761 0.098843 0.0227962 -0.162887 -0.0227955 0.095045 -0.21496 -0.596977 0.741627 -0.596977 0.847852 0.943158 0 0.21565 0.41625 0.06036 0.41625 0.814723 -0.265965 -0.399916 -0.441982 -0.734448 0.566124 -0.716591 0.734448 -0.331272 0 -0.465735 -0.480716 0.581881 -0.961362 0.581881 -0.92036 0.393331 -0.928822 0.852276 0.928823 -0.571183 -0.535413 0.789559 0.442791 -0.861661 0.143848 0.89346 -0.861661 0.795825 0 0.399108 0.52577 0.806535 0.69138 -0.525769 0.973847 -0.88769 0.052107 0.696694 -0.0342733 0.626272 -0.0342738 0.994108 0.738939 -0.0845074 0.702182 -0.0845085 -0.505053 -0.37123 0 0.05087 -0.630413 0.170569 0.31216 -0.630413 -0.887018 0.152552 0.605767 -0.215791 -0.491239 0.210754 0.491239 0.787853 0
0 0 0 0.355659 0.933965 0.187071 0.110437 0.18707 0.866547 0.108337 0.585246 0.349334 0.585244 0.470917 -0.665203 0.0644461 -0.611989 -0.844583 0.497941 -0.972644 0.844583 0.619397 -0.653134 -0.548745 -0.63796 0.67841 0.917294 -0.67841 0.821836 -0.721063 0.258722 -0.039918 0.258722 -0.200363 0.304222 0 -0.732737 0.343103 -0.223624 0.343104 -0.56112 -0.335097 0.82842 -0.764517 0.292307 0.807614 -0.584614 -0.292308 -0.943028 0 0.168038 0.789299 0.362502 0.253123 0.362503 -0.003999 -0.915435 0.354407 -0.324551 -0.354407 0.799445 -0.167226 -0.38493 0.203222 -0.322777 0.431269 -0.41491 -0.322776 0.511407 0 -0.523871 -0.761172 0.590581 -0.710203 0.761172 -0.080055 -0.101313 -0.996034 0.03436 -0.991162 -0.2862 -0.991163 0.072683 -0.519516 -0.0561693 0.353175 -0.0561687 0.581614 0.77018 0 -0.85837 -0.756662 -0.325484 -0.422488 -0.756662 -0.152189 0.851205 0.776332 -0.937112 0.826626 0.013433 -0.826626 0.274495 0
0 0 0 0.666817 0.231877 -0.220034 0.986756 -0.220035 0.377155 -0.91235 0.788133 -0.238058 0.788133 -0.676393 -0.495518 -0.997903 -0.452098 -0.425129 0.750095 -0.224396 0.425128 -0.729435 0.409944 0.835944 -0.7637 -0.734331 -0.363371 0.734331 -0.56174 -0.658681 -0.759394 -0.669624 -0.759395 0.49092 0.133799 0 0.645439 0.842031 0.972805 0.842031 -0.146185 0.903866 -0.392156 0.469218 0.612489 -0.165116 0.380425 -0.61249 -0.03094 0 0.868823 -0.381994 -0.728017 0.108216 -0.728016 0.391053 0.08526 -0.108098 -0.410233 0.108097 0.18611 0.82787 -0.47794 0.873291 -0.391609 0.890682 0.171983 -0.391608 0.32423 0 -0.752511 0.379714 -0.026762 0.132686 -0.379714 0.212633 -0.449158 0.072118 0.716545 0.128152 0.725171 0.128153 -0.080414 0.429037 0.994838 0.61823 0.994838 -0.637689 0.518664 0 -0.510502 0.173326 -0.930036 0.850917 0.173326 -0.435932 0.502175 0.174228 0.274326 0.274542 -0.977447 -0.274542 -0.551307 0`

**Comment by psadil** [comment]
@meet10may I think this issue was closed now that 06d0a2a3a59d7c3b4d1f095ee2de83c30eab3e79 has been merged into master. If not, please reopen
