### ISSUE TITLE
Update fMRIPrep to version that includes missing `minc_modify_header`

### ISSUE THREAD

**Issue by psadil** [a2cps/mri_imaging_pipeline#297]
Several (77) fMRIPrep jobs are failing because of a missing FS file

```
$  grep -l -m1 "spawn: exec of minc_modify_header failed: No such file or directory" */fmriprep*log | wc -l
77
```

This file has been added in the docker for 24.1.1: https://github.com/nipreps/fmriprep/releases/tag/24.1.1

**Comment by JoshuaUrrutia** [comment]
deleted logs
