### ISSUE TITLE
UC10036V3 requires manual running

### ISSUE THREAD

**Issue by psadil** [a2cps/mri_imaging_pipeline#41]
See https://a2cps-pain.slack.com/archives/C02JP3G763X/p1636326379076900

Both their PatientName and zip file are named incorrectly, with `UC100363V3`. For now, they require rerunning. This case may warrant a manual, if/else clause in the heudiconv app, as in, e.g., #37

**Comment by torwager** [comment]
Thanks, Patrick.  The local staff at UC are on this list and notified in this email, right?

Tor

**Comment by psadil** [comment]
@torwager I actually didn't think that they were. I had written this here because I thought that the participant was uploaded long enough ago that UC won't be able to resend with a correct name, and so we would want to update the heudiconv app to handle the incorrect name. Though, I have since learned that at least @JoshuaUrrutia disagrees with editing the code in this situation, and I think we'll standardize a solution for this case in the next DIRC meeting -- this case of having DICOMs with an incorrect PatientName tag that the sites can't resend

**Comment by torwager** [comment]
Thanks, Patrick.  I think it’s important for the sites to know anyway, as we want to prevent future errors.

Cheers,
Tor

**Comment by psadil** [comment]
That makes sense. In similar cases, there's been a step in which @jcf2 contacted the site to see whether a re-upload was possible. In making this issue on github, I didn't wait for that contact. That was being too hasty, as it sounds like they can upload this participant with a corrected name. 

Closing this issue for now, considering that there's no longer indication that this participant will need manual handling.
